language: android

android:
  components:
    - tools
    - android-19
    - extra-android-support
    - extra-android-m2repository

jdk: oraclejdk7

env:
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a



before_install:

   - gem install calabash-android
   - gem install calabash-cucumber
   # Create and start emulator
   - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
   #- emulator -avd test -no-skin -no-audio -no-window &

cache:
  - apt

install:
  #- TERM=dumb ./gradlew assemble

before_script:
  # Make sure the emulator has started before running tests
  - chmod +x wait_for_emulator
  - ./wait_for_emulator


script:
  - calabash-android resign features/bin/app-debug-unaligned.apk
  - calabash-android build features/bin/app-debug-unaligned.apk
  - calabash-android run features/bin/app-debug-unaligned.apk