language: android

android:
  components:
    - sys-img-armeabi-v7a-android-19
    - build-tools-20.0.0

jdk: oraclejdk7

env:
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a


cache:
  - apt

before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - gem install calabash-android
    - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
    - mksdcard 265M sdcard
    - emulator -avd test -no-audio -no-boot-anim -sdcard sdcard &
    - android-wait-for-emulator
    - adb shell input keyevent 82
    - sleep 20



script:
  - adb start-server
  - adb devices
  - ./gradlew build
  - calabash-android resign app/build/outputs/apk/app-release-unsigned.apk
  - calabash-android run app/build/outputs/apk/app-release-unsigned.apk