language: android

android:
  components:
    #- tools
    #- android-19
    - sys-img-armeabi-v7a-android-19
    - build-tools-20.0.0
    #- extra-android-support
    #- extra-android-m2repository

jdk: oraclejdk7

env:
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a



before_install:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - gem install calabash-android
  - gem install cucumber
  
cache:
  - apt

install:

 # - TERM=dumb ./gradlew assemble

before_script:
   - chmod +x wait_for_emulator
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 45

  - ./wait_for_emulator
  - adb shell input keyevent 82 &


script:
  - adb start-server
  - adb devices
  - ./gradlew connectedCheck --info
  - ./gradlew build
  - calabash-android resign features/bin/app-debug-unaligned.apk
  #- calabash-android build features/bin/app-debug-unaligned.apk
  - travis_wait calabash-android run features/bin/app-debug-unaligned.apk
