language: android

android:
  components:
    - tools
    - android-19
    #- extra-android-support
    #- extra-android-m2repository

jdk: oraclejdk7

env:
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a



before_install:

   
   # Create and start emulator
   - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
   - emulator -avd test -no-skin -no-audio -no-window &

cache:
  - apt

install:
  - echo no | android create avd -n emulator -t android-19 --skin WVGA800 --force --abi armeabi-v7a
  - TERM=dumb ./gradlew assemble
  - gem install calabash-android
  - gem install calabash-cucumber

before_script:
   # Make sure the emulator has started before running tests
 sh -e /etc/init.d/xvfb start
 sleep 3 
 # give xvfb some time to start 
 emulator -avd emulator -prop persist.sys.language=en -prop persist.sys.country=US -noaudio -no-boot-anim &
 sleep 45


script:
    adb kill-server
    adb start-server
    adb devices
  #- calabash-android resign features/bin/app-debug-unaligned.apk
  #- calabash-android build features/bin/app-debug-unaligned.apk
  adb install -r features/bin/app-debug-unaligned.apk
  - travis_wait calabash-android run features/bin/app-debug-unaligned.apk
